services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - lbt-healthcheck
      - lbt-authentication-service
      - lbt-authorization-service
    networks:
      - app-net

  lbt-healthcheck:
    build:
      context: .
      dockerfile: ./healthcheck/Dockerfile
    container_name: lbt-healthcheck
    restart: unless-stopped
    env_file:
      - ./.env
    expose:
      - "3000"
    networks:
      - app-net
  lbt-authentication-service:
    build:
      context: .
      dockerfile: ./authentication-service/Dockerfile
    container_name: lbt-authentication-service
    restart: unless-stopped
    env_file:
      - ./.env
    expose:
      - "3000"
    networks:
      - app-net
  lbt-authorization-service:
    build:
      context: .
      dockerfile: ./authorization-service/Dockerfile
    container_name: lbt-authorization-service
    restart: unless-stopped
    env_file:
      - ./.env
    expose:
      - "3000"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
